[profile.default]
solc_version = "0.8.9"
auto_detect_solc = false
optimizer = true
optimizer_runs = 500
src = 'contracts'
out = 'out'
test = 'test-foundry'
libs = ["lib"]
verbosity = 1
via_ir = false
auto_detect_remappings = true
ffi = false
remappings = [
    '/=contracts',
    'forge-std/=lib/forge-std/src/'
]
